# Generated by Django 3.1.3 on 2024-07-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larrain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='name',
            new_name='nombre',
        ),
    ]
